### ISSUE TITLE
User Story: Create Property Listing

### ISSUE THREAD

**Issue by ianmeigh** [ianmeigh/property-direct-frontend#12]
_As a_ **User (Seller)**, _I can_ **create a property listing** _so that_ **others can view my listing, make enquires and I can sell my property**.

## Acceptance Criteria

- Property listing information can be entered into a form and saved to the API.
- Property listing information is validated with any errors reported to the user.

## Tasks

- [x] - Add create property link in NavBar.
- [x] - Add create property form with cancel and submit options.
- [x] - Ensure data is saved to the database on submission.

## Epic

Property - #3
