### ISSUE TITLE
User Story: Edit Property Listing

### ISSUE THREAD

**Issue by ianmeigh** [ianmeigh/property-direct-frontend#16]
_As a_ **User (Seller)**, _I can_ **edit a property listing** _so that_ **I can to update information or mark the property as sold**.

## Acceptance Criteria

- A property can be edited using a link within the individual property view.
- A property listing will be displayed in an editable format with existing information populated.
- The edit can be cancelled, which will return the user to the previous page.
- When saved, the information in the listing will be updated to reflect any changes made.

## Tasks

- [x] - Create a link to edit a property listing, visible to the listing owners.
- [x] - Create an edit property form with cancel and submit options.
- [x] - Ensure database information is updated on submission.

## Epic

Property - #3
