### ISSUE TITLE
User Story: Bookmark Property

### ISSUE THREAD

**Issue by ianmeigh** [ianmeigh/property-direct-frontend#18]
_As a_ **User**, _I can_ **bookmark a property** _so that_ **I can review it at a later time and more easily track updates to the listing**.

## Acceptance Criteria

- Users can bookmark properties they are interested in using a link in both the property list view and detail view.

## Tasks

- [x] - Add a bookmark button to the property component.
- [x] - Add a button state to reflect when a property has been bookmarked.
- [x] - Ensure data is saved to the database.

## Epic

Property - #3
