### ISSUE TITLE
User Story: Property Search (Advanced)

### ISSUE THREAD

**Issue by ianmeigh** [ianmeigh/property-direct-frontend#25]
_As a_ **User**, _I can_ **specify a point of origin (postcode) and a radius, combined with other filters** _so that_ **narrow my search to an area I am interested in**.

## Acceptance Criteria

- Search options should be present on the main property page, so a user can narrow their search..

## Tasks

- [x] - Create a Property Search component
- [x] - Use Postcode and Radius as query parameters which when passed to the API, filter the Property queryset.
- [x] - Postcode and Radius should be validated.
- [x] - Add additional Filters to narrow property results further based on budget and other property criteria specified in the property model.
- [x] - Display search results with distance from point of origin.
- [x] - List the number of search results returned.

## Epic

Property - #3
