### ISSUE TITLE
User Story: Profile Description

### ISSUE THREAD

**Issue by ianmeigh** [ianmeigh/property-direct-frontend#31]
_As a_ **User**, _I can_ **maintain a profile description** _so that_ **I can help introduce myself or my brand (seller) and help other users learn more about me**.

## Acceptance Criteria

- Allow users to add and edit a profile description.

## Tasks

- [x] - Create an edit button for the profile.
- [x] - Create an edit profile form.
- [x] - Ensure information is updated in the database.

## Epic

Profile and Account Management - #4
