### ISSUE TITLE
User Story: Profile Image

### ISSUE THREAD

**Issue by ianmeigh** [ianmeigh/property-direct-frontend#32]
_As a_ **User**, _I can_ **maintain a profile image** _so that_ **I can personalize my site experience and/or introduce my brand (seller) to other users**.

## Acceptance Criteria

- Allow users to upload an Avatar.
- Avatar should be displayed next to their content throughout the site.

## Tasks

- [x] - Create a button within the profile edit form to allow image selection.
- [x] - Display a preview of the selected image.
- [x] - Validate the image.
- [x] - Ensure information is updated in the database.

## Epic

Profile and Account Management - #4
