### ISSUE TITLE
User Story: Follow Sellers

### ISSUE THREAD

**Issue by ianmeigh** [ianmeigh/property-direct-frontend#35]
_As a_ **User**, _I can_ **follow sellers** _so that_ **see all of the properties they have listed**.

## Acceptance Criteria

- Users can follow sellers using a link on the seller's profile page.

## Tasks

- [x] - Add a follow button to the seller's profile.
- [x] - Change the button state to reflect when a profile has been followed by a user.
- [x] - Ensure data is saved to the database.

## Epic

Profile and Account Management - #4
