### ISSUE TITLE
User Story: Create Articles

### ISSUE THREAD

**Issue by ianmeigh** [ianmeigh/property-direct-frontend#39]
_As an_ **Admin**, _I can_ **create articles** _so that_ **share information relevant to property sales and the website**.

## Acceptance Criteria

- Article content can be entered into a form and saved to the API.
- Article content is validated with any errors reported to the user.

## Tasks

- [ ] - Add create article link in NavBar.
- [ ] - Add create article form with cancel and submit options.
- [ ] - Ensure data is saved to the database on submission.

## Epic

Articles - #5
