### ISSUE TITLE
User Story: Edit Articles

### ISSUE THREAD

**Issue by ianmeigh** [ianmeigh/property-direct-frontend#40]
_As an_ **Admin**, _I can_ **I can edit articles** _so that_ **I can correct mistakes or update content**.

## Acceptance Criteria

- An article can be edited using a link within the individual article view.
- An article listing will be displayed in an editable format with existing information populated.
- The edit can be canceled, which will return the user to the previous page.
- When saved, the information in the article will be updated to reflect any changes made.

## Tasks

- [ ] - Create a link to edit an article listing, visible to the article owner.
- [ ] - Create an edit article form with cancel and submit options.
- [ ] - Ensure database information is updated on submission.

## Epic

Articles - #5
