### ISSUE TITLE
User Story: Comments

### ISSUE THREAD

**Issue by ianmeigh** [ianmeigh/property-direct-frontend#45]
_As a_ **User**, _I can_ **comment on articles** _so that_ **share my opinion**.

## Acceptance Criteria

- Comments can be created on individual articles.

## Tasks

- [ ] - Add comment form.
- [ ] - Ensure data is saved to the database on submission.
- [ ] - Ensure comments are displayed on the article detail view and implement an infinite scroll component to load paginated comments from the API when a user scrolls down the page.

## Epic

Articles - #5
