### ISSUE TITLE
User Story: Navigation Bar

### ISSUE THREAD

**Issue by ianmeigh** [ianmeigh/property-direct-frontend#6]
_As a_ **User**, _I can_ **view the navigation bar on every page** _so that_ **I can easily navigate the site and know my current location in the site structure**.

## Acceptance Criteria

- The navigation bar should be visible on every page and inform users of their current location in the site structure.
- The navigation bar should present a different layout suited to the screen size it is being viewed from.

## Tasks

- [x] - Create NavBar component
- [x] - Configure basic site routing
- [x] - Make NavBar responsive for smaller screens

## Epic

Navigation - #1
