### ISSUE TITLE
User Story: Sign In

### ISSUE THREAD

**Issue by ianmeigh** [ianmeigh/property-direct-frontend#8]
_As a_ **User**, _I can_ **log in to my account ** _so that_ **I can use the service using my existing credentials**.

## Acceptance Criteria

- Users can sign in using the credentials they used to sign up.

## Tasks

- [x] - Create sign in link on NavBar
- [x] - Create sign in form
- [x] - Create redirect so successful sign-up will redirect to sign in form
- [x] - Create a redirect so that successful sign in will redirect to the home page

## Epic

Authentication - #2
